### ISSUE TITLE
Explicit URL structure

### ISSUE THREAD

**Issue by barklund** [mbi/django-rosetta#104]
I was wondering why the system works with session'ed attributes like current language and filter.

I'm pretty sure there is some reason behind that, but I would personally prefer a more explicit URL structure where you edit `/rosetta/fr/?filter=fuzzy`. This would allow deep-linking, allow for editing (or simply browsing) multiple languages in separate tabs (and not separate browsers as is now required) and just make it more transparent (and thus more pythonic).

Would there be an interest in (me working on) changing this?

**Comment by mbi** [comment]
Hi Morten,

the current URL structure is an absolute mess, and if there used to be a reason behind it, it was lost in time. So yes, I think a more restful URL architecture would be greatly appreciated. Beware, though, as it'll likely affect most of the views, all the tests and so on. Here be dragons.

There is a 3 year old pull request that was never merged (probably because it was a monster patch with a lot of added commits that I wouldn't want included) here: https://github.com/mbi/django-rosetta/pull/4 

I think it's important to stress that all the tests will need to be ported, and will need to pass for such an important change to be merged.

Thank you in advance, if you wish to work on this. Do not hesitate to send intermediary pull requests, if you would like some help and/or feedback.

**Comment by barklund** [comment]
Hi Marco,

If that's the case, I'll try to clean things up and give the tests a once-over as well.

But I had problems actually getting the tests to run. There is a `runtests.sh`, but it installs `Django==1.3` (and the readme says Django 1.4+ only) and it did not install `requests`, which was clearly in use. Is there some other (proper) way of running the tests, that I'm missing?

I would like to help out, but it looks like some (a lot of) spring cleaning is needed in the general structure of the project.

On a side note, I have many other ideas for making this more capable and useful as I use it on a fairly big project with (currently) 12 languages and multiple translators for each.

**Comment by mbi** [comment]
Ah yes, use runtests_multi_venv, which is maintained. The simple runtests script needs to be removed.

Thanks.   

## 

Marco Bonetti
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jbaldivieso** [comment]
Hi Marco,
I'm looking into reviving this issue again. A few questions for you:

* Are there any current efforts underway I should be aware of?
* How would you feel about a shift to class-based views?
* Is there a quicker way to run the tests, say in just one version of Django? Using tox seems to take about five minutes per run, and it would be nice to run something more quickly more often as I refactor.

Thanks!

Jon

**Comment by mbi** [comment]
Hi Jon,


>     Are there any current efforts underway I should be aware of?

None, I'm afraid.

>     How would you feel about a shift to class-based views?

Sure, if you think that shifting to CBVs would ease the transition to a better URL structure I'm definitely in favor!

>     Is there a quicker way to run the tests, say in just one version of Django? Using tox seems to take about five minutes per run, and it would be nice to run something more quickly more often as I refactor.
> 

Absolutely, if you only want to test against Py3 and Django 1.11 for example you can:

```
source .tox/py36-django111/bin/activate
```

Then run tests after each set of changes:
```
python testproject/manage.py test
```

**Comment by jbaldivieso** [comment]
Great, thank you, Marco!

**Comment by jbaldivieso** [comment]
@mbi, now that 0.8.0 has been released, can this issue be closed out?

**Comment by mbi** [comment]
@jbaldivieso yup, cheers!

**Comment by merwok** [comment]
Great news! ✨
