### ISSUE TITLE
Translation page broken in Django 3.1.2

### ISSUE THREAD

**Issue by realsuayip** [mbi/django-rosetta#248]
- Which version of Django are you using?: 
3.1.2
- Which version of django-rosetta are you using?:
0.9.4
- Have you looked trough [recent issues](https://github.com/mbi/django-rosetta/issues?utf8=%E2%9C%93&q=is%3Aissue) and checked this isn't a duplicate?
Yes

In Django 3.1.2, the translation page is broken (see screenshot), presumably because of the changes made in this pull 
request: https://github.com/django/django/pull/13409/

`display: flex` rule in `#changelist` block seems to be the problem.

![screenshot](https://user-images.githubusercontent.com/17948971/94856440-ac47d300-0438-11eb-9eb2-3b872a6cd1e1.PNG)

**Comment by mondeja** [comment]
I can reproduce this with the same version of Django. I have solved this defining the next rule extending the rosetta template, but this need to be properly handled in the library or in Django:

```css
#changelist {
  display: block !important;
}
```
EDIT: Seems the bug is coming from [this commit](https://github.com/django/django/commit/8ee4bb6ffcb3346c0fa8fb194986fbf9edadc822).

**Comment by mbi** [comment]
Thank you both for tracking this down.

**Comment by mbi** [comment]
(Just released 0.9.5, including this fix.)
