### ISSUE TITLE
Disable fuzzy strings

### ISSUE THREAD

**Issue by kundo** [mbi/django-rosetta#25]
Having two different kinds of translations (fuzzy, and untranslated) confuses new translators in our code-base. So we would like to disable the fuzziness matching, and show all strings as untranslated instead. So this is a feature request for a setting that does this.

Ideally, this should be done in Django, but they have firmly stated that feature as wontfix: https://code.djangoproject.com/ticket/10852 - so I'm hoping you will take up this usability issue instead :)

**Comment by mbi** [comment]
Nope, sorry, wontfix either :(

**Comment by EmilStenstrom** [comment]
@mbi: Any reason?

**Comment by mbi** [comment]
@EmilStenstrom @kundo fuzzy strings are an inherent part of the gettext translation process, and they really make sense and are useful, more often than not. 

I understand that this might confuse some translators, but in my experience in using Rosetta with non technical translators (we usually set it up so that our clients translate their websites themselves) is that a few lines of documentation on Rosetta and a few explanatory screenshots helps them understand the purpose of fuzzy strings and the translation process in general.

If documentation won't do, I would like to suggest three possible solutions to your problem:
- write a python script that parses the po catalogs after they have been generated by Django and clear the fuzzy flag (and clear the suggested translation)
- fork Rosetta, add the option yourself
- set up a bounty and sponsor the development of this option

I hope you'll understand.

**Comment by EmilStenstrom** [comment]
@mbi: That's a great reply, and I fully understand your rationale. Thanks for taking it one step further, and suggesting how we could solve our specific problem.

**Comment by fabiomontefuscolo** [comment]
For those trying to remove fuzzy, I could remove in this way.

``` bash
sed -i -z -r -e 's/(#[^\n]+\n)*(#, fuzzy[^\n]*\n)(#\| msgid[^\n]+\n)(#[^\n]+\n)*(msgid[^\n]+\n)("[^"]+"\n)*(msgstr[^\n]+\n)("[^"]+"\n)*//g' \
    `find locale -name "*.po"`
```
