### ISSUE TITLE
Interface Glitches on clicks and search

### ISSUE THREAD

**Issue by elioscordo** [mbi/django-rosetta#91]
Hi,
The interface is redirecting tot he language list page when clicking and search.

Makes it unusable.. any help?

**Comment by mbi** [comment]
Hi, which version of Rosetta? And Django? And on the devserver or a prod environment? What is your settings. ROSETTA_STORAGE_CLASS? And your settings.SESSION_BACKEND and settings.CACHES?

**Comment by elioscordo** [comment]
Django 1.5.4 last release
Rosetta las release (downloaded today)

I did not defined none of those params:

ROSETTA_STORAGE_CLASS default in rosetta
settings.SESSION_BACKEND default in django
settings.CACHES  default in django

**Comment by elioscordo** [comment]
Any update? Previous rosetta is not supported in django 1.5 .. I am back to file editing. 
Please help.

**Comment by mbi** [comment]
Yes, I was wondering… what kind of server are you running? development server, gunicorn + nginx, apache2 + mod_wsgi, … ?

**Comment by elioscordo** [comment]
apache2 + wsgi

**Comment by mbi** [comment]
Alright, so this is is a multi-process environment: you have several apache runners, but since your settings.CACHES uses the default `LocMemCache` backend, each process has it's own cache instance. So one process will handle a request, write some Rosetta stuff into the cache, but when the next request comes it won't find that data, because it's in another's process cache.

Possible solutions: 
- use a real cache backend, e.g. `memcached`. See https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-CACHES
- set settings.ROSETTA_STORAGE_CLASS = 'rosetta.storage.SessionRosettaStorage', but beware for huge PO files.

All this is actually explained on the project page: https://github.com/mbi/django-rosetta#storages

Hope this helps.
